Include DaSL contact info and basic logo in header
FredHutch/trm-calculator pull request #9
Opened 2024-05-30 21:37 UTC by vsriram24

Included contact info for the FH DaSL email at the bottom of the app as well as a draft logo for the application in the dashboard header. I will handle increasing size of logo and the layout of dashboard in issue 4 ("pretty")

2024-05-30 22:17 UTC, monicagerber requested changes

2024-05-30 22:17 UTC, monicagerber commented on .Rhistory
Remove from git tracking, don't add this file

Can add .Rhistory to .gitignore

2024-05-30 22:17 UTC, monicagerber commented on app/www/fhLogo.png
If we're not using this logo, let's not track in the repo. same with below.

2024-05-30 22:17 UTC, monicagerber commented on app/www/trmHeader.png
I like this logo but we may get push back from branding in the future. Let's use this instead of "trmDasL.png". Can you put something like "developed by the Data Science Lab" (with a link) at the bottom of the app or in the left-side menu?

2024-05-30 22:17 UTC, monicagerber commented on app/www/trmDaSL.png
This will anger branding people more : (
They don't like it when we put "Data Science Lab" below the Fred hutch logo

2024-05-30 23:23 UTC, vsriram24 commented
@monicagerber requested changes have been incorporated

2024-06-05 18:19 UTC, monicagerber approved these changes
I'm sorry, I didn't realize that the logo was in the corner and not across the whole page. Could you use just the FH logo? (app/www/fhLogo.png)

Looks ready to merge after that.

2024-06-05 18:19 UTC, monicagerber commented on app/app.R
> +      ". For questions or feedback regarding this application, email DaSL at ",
```suggestion
      ". For questions or feedback regarding this application, email DaSL Translational Analytics at ",
```

2024-06-05 18:19 UTC, monicagerber commented on app/app.R
> +  daslEmail <- a("data@fredhutch.org", href="mailto:data@fredhutch.org")
```suggestion
  daslEmail <- a("analytics@fredhutch.org", href="mailto:analytics@fredhutch.org")
```

2024-06-05 18:44 UTC, merged